//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmonUser.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class UsuariosEntities : DbContext
    {
        public UsuariosEntities()
            : base("name=UsuariosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Applications> Applications { get; set; }
        public DbSet<Memberships> Memberships { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<tusuarios> tusuarios { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Profiles> Profiles { get; set; }
        public DbSet<UsersInRoles> UsersInRoles { get; set; }
        public DbSet<vw_MemberShip_datos> vw_MemberShip_datos { get; set; }
    
        public virtual ObjectResult<sp_MemberShip_Datos_Result> sp_MemberShip_Datos(string idaplicacion, string busqueda_personal)
        {
            var idaplicacionParameter = idaplicacion != null ?
                new ObjectParameter("idaplicacion", idaplicacion) :
                new ObjectParameter("idaplicacion", typeof(string));
    
            var busqueda_personalParameter = busqueda_personal != null ?
                new ObjectParameter("busqueda_personal", busqueda_personal) :
                new ObjectParameter("busqueda_personal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MemberShip_Datos_Result>("sp_MemberShip_Datos", idaplicacionParameter, busqueda_personalParameter);
        }
    
        public virtual int upd_bloqueo_membership(string iduser, Nullable<bool> op, Nullable<bool> apro)
        {
            var iduserParameter = iduser != null ?
                new ObjectParameter("iduser", iduser) :
                new ObjectParameter("iduser", typeof(string));
    
            var opParameter = op.HasValue ?
                new ObjectParameter("op", op) :
                new ObjectParameter("op", typeof(bool));
    
            var aproParameter = apro.HasValue ?
                new ObjectParameter("apro", apro) :
                new ObjectParameter("apro", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_bloqueo_membership", iduserParameter, opParameter, aproParameter);
        }
    
        public virtual ObjectResult<sel_res_usuarios_Result> sel_res_usuarios(string usuario, string guid)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var guidParameter = guid != null ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_res_usuarios_Result>("sel_res_usuarios", usuarioParameter, guidParameter);
        }
    }
}
