//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmonUser.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class dbSigaEntities : DbContext
    {
        public dbSigaEntities()
            : base("name=dbSigaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vw_plantilla> vw_plantilla { get; set; }
    
        public virtual ObjectResult<sp_busca_personal_plantilla_siga_Result> sp_busca_personal_plantilla_siga(string busqueda)
        {
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_busca_personal_plantilla_siga_Result>("sp_busca_personal_plantilla_siga", busquedaParameter);
        }
    }
}
