//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmonUser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tusuarios
    {
        public int IdPersonaMembership { get; set; }
        public Nullable<int> idtpersonal { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string login { get; set; }
        public string passrowd { get; set; }
        public Nullable<int> id_centro { get; set; }
        public string Nombre { get; set; }
    }
}
