//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmonUser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_plantilla
    {
        public int PersonalID { get; set; }
        public int idtccentro { get; set; }
        public string centro { get; set; }
        public int idtccentrotrabajo { get; set; }
        public string centrotrabajo { get; set; }
        public string rfc { get; set; }
        public string curp { get; set; }
        public string telefono { get; set; }
        public string paterno { get; set; }
        public string materno { get; set; }
        public string nombre { get; set; }
        public string Busqueda { get; set; }
        public string nombrecompleto { get; set; }
        public int idtcestatuslaboral { get; set; }
        public System.DateTime fechanacimiento { get; set; }
        public decimal EdadCalculada { get; set; }
        public int AdscripcionID { get; set; }
        public string nopersonal { get; set; }
        public string ClaveIFE { get; set; }
        public string noimss { get; set; }
        public string genero { get; set; }
        public string estadocivil { get; set; }
        public string lugarnacimiento { get; set; }
        public int idtcgradoestudio { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public string telefonorecados { get; set; }
        public int idtcentidadfederativa { get; set; }
        public string abreviacion { get; set; }
        public string localidad { get; set; }
        public string cartillasmn { get; set; }
        public System.DateTime fechaalta { get; set; }
        public Nullable<int> antiguedad { get; set; }
        public string cuip { get; set; }
        public string numeroprogramatico { get; set; }
        public Nullable<int> GeneracionID { get; set; }
        public Nullable<int> FuncionID { get; set; }
        public string noplaza { get; set; }
        public string tipocontrato { get; set; }
        public int idtccategoria { get; set; }
        public string exmilitar { get; set; }
        public string descripcionexmilitar { get; set; }
        public string tipoelemento { get; set; }
        public string categoria { get; set; }
        public int idtcmunicipio { get; set; }
        public string MunicipiosNombre { get; set; }
        public string gradodescripcion { get; set; }
        public string entidadfederativa { get; set; }
        public int idtcsituacionlab { get; set; }
        public string nombresituacionlaboral { get; set; }
        public string DiasPendientesV { get; set; }
        public string funcion { get; set; }
        public string ctmatriz { get; set; }
        public string cttrabajo { get; set; }
        public string ct_ubicacion { get; set; }
        public string ub_fisicaactual { get; set; }
        public string sub_ubicacion { get; set; }
        public string base_generalpuesto { get; set; }
        public int idtcplazatipo { get; set; }
        public string tipoplaza { get; set; }
        public Nullable<int> idtcctubicacion { get; set; }
        public string ctubfisica { get; set; }
        public Nullable<int> idtcubfisica { get; set; }
        public string ubfisica { get; set; }
        public Nullable<int> idsububfisico { get; set; }
        public string sububfisica { get; set; }
        public int idtctiporh { get; set; }
        public string tiporh { get; set; }
        public string estatus { get; set; }
        public string estatusmotivo { get; set; }
        public string mando { get; set; }
    }
}
